version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "pytxdb_test"
      POSTGRES_USER: "pytxdb"
      POSTGRES_PASSWORD: "pytxdb"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - main
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: "pytxdb_test"
      MARIADB_USER: "pytxdb"
      MARIADB_PASSWORD: "pytxdb"
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - main
    restart: unless-stopped

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "pytxdb_test"
      MYSQL_USER: "pytxdb"
      MYSQL_PASSWORD: "pytxdb"
    ports:
      - "127.0.0.1:3308:3308"
    networks:
      - main
    restart: unless-stopped
